name: tr11-176B-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py38h578d9bd_0
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng>=10.3.0
  - nccl=2.10.3.1=hdc17891_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1q=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - best-download==0.0.9
    - black==21.4b0
    - cachetools==5.0.0
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - colorama==0.4.4
    - cython==0.29.28
    - dataproperty==0.55.0
    - datasets==1.15.1
    - dill==0.3.4
    - dynet38==2.1
    - filelock==3.6.0
    - flatbuffers==2.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - gast==0.5.3
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - h5py==3.6.0
    - hjson==3.0.2
    - huggingface-hub==0.9.0
    - idna==3.3
    - importlib-metadata==4.11.2
    - iniconfig==1.1.1
    - isort==5.10.1
    - jieba==0.42.1
    - joblib==1.1.0
    - jsonlines==2.0.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - lm-dataformat==0.0.20
    - lm-eval==0.2.0
    - markdown==3.3.6
    - mbstrdecoder==1.1.0
    - mock==4.0.3
    - msgfy==0.2.0
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - mypy-extensions==0.4.3
    - nagisa==0.2.7
    - ninja==1.10.2.3
    - nltk==3.7
    - numexpr==2.7.2
    - numpy==1.22.3
    - oauthlib==3.2.0
    - openai==0.6.4
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.1
    - parameterized==0.8.1
    - pathspec==0.9.0
    - pathvalidate==2.5.0
    - pillow==9.0.1
    - pluggy==0.13.1
    - portalocker==2.4.0
    - protobuf==3.19.4
    - psutil==5.9.0
    - py==1.11.0
    - py-cpuinfo==8.0.0
    - py-spy==0.3.11
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.2
    - pycountry==20.7.3
    - pydantic==1.9.1
    - pyparsing==3.0.7
    - pytablewriter==0.58.0
    - pytest==6.2.3
    - pytest-instafail==0.4.2
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2022.3.2
    - rehash==1.0.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.0.4
    - rsa==4.8
    - sacrebleu==1.5.0
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - semantic-version==2.9.0
    - sentencepiece==0.1.96
    - setuptools-rust==1.1.2
    - six==1.16.0
    - sqlitedict==1.6.0
    - tabledata==1.3.0
    - tcolorpy==0.1.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.25.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tf-slim==1.1.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - tomli==2.0.1
    - tqdm==4.63.0
    - tqdm-multiprocess==0.0.11
    - typepy==1.3.0
    - typing-extensions==4.1.1
    - ujson==5.2.0
    - urllib3==1.26.8
    - werkzeug==2.0.3
    - wrapt==1.14.0
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.7.0
    - zstandard==0.15.2